#################################################
# Node.js example for Actions                   #
#                                               #
# Note: This workflow will do an install of     #
# node dependencies, build the source code and  #
# run tests across different versions of node   #
#################################################

name: Node.js CI

# Run when a change is pushed
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Relative path to your .npm folder
  SOURCE-DIR: ./PATH/TO/YOUR/NPM/FILES/

jobs:
          
  build:

    runs-on: ubuntu-latest
    
    # Run across multiple node.js versions
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # Cache node modules
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: $SOURCE-DIR
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    # Install dependencies          
    - name: Install
      run: npm install
    
    # Run the linting script (this needs to be pre-configured)
    - name: Linting
      run: npm run lint
      
    # Build the node.js application
    - name: Build
      run: npm run build
    
    # Run the tests
    - name: Test
      run: npm test
